POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
  "username": "admin",
  "password": "test"
}

###
POST http://localhost:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
  "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc0NjU3MDI1MCwiaWF0IjoxNzQ2NDgzODUwLCJqdGkiOiJhOThiOWZkODBlMmY0MzFmODhiY2JlY2Y3NDNlMjY3OCIsInVzZXJfaWQiOjF9.EtbZFucmLZFCtLF3FemAxf29UI2vRu-1C-c-r8kUa3o"
}

###
GET http://localhost:8000/products/ HTTP/1.1

###
POST http://localhost:8000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ2NDgxNzMyLCJpYXQiOjE3NDY0ODE0MzIsImp0aSI6Ijc1MTE4MDM4OWE0YjQ1OGM4NmNlYjFmODcwOGQzNDA4IiwidXNlcl9pZCI6MX0.-tm_V-cbeRVGsmSYOjxAyCps_beKRuiqt4RAwUU4gGs

{
  "name": "Television",
  "price": 500,
  "stock": 20,
  "description": "A large screen TV"
}

###
GET http://localhost:8000/users-orders/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ2NDgxNzMyLCJpYXQiOjE3NDY0ODE0MzIsImp0aSI6Ijc1MTE4MDM4OWE0YjQ1OGM4NmNlYjFmODcwOGQzNDA4IiwidXNlcl9pZCI6MX0.-tm_V-cbeRVGsmSYOjxAyCps_beKRuiqt4RAwUU4gGs
